# Sentinel Configuration
# Simple YAML configuration for HyperFleet Sentinel service
# This replaces the previous CRD-based configuration approach

# === RESOURCE MONITORING ===
resource_type: clusters  # Resource to watch: clusters, nodepools, manifests, workloads

# === POLLING CONFIGURATION ===
poll_interval: 5s         # How often to check the API
backoff_not_ready: 10s    # Wait time for resources still provisioning
backoff_ready: 30m        # Wait time for stable/ready resources

# === SHARDING (optional) ===
shard_selector: "shard=1"  # Label selector for horizontal scaling

# === HYPERFLEET API ===
hyperfleet_api:
  endpoint: https://api.hyperfleet.example.com
  timeout: 30s
  # token: Override via HYPERFLEET_API_TOKEN="secret-token"

# === MESSAGE BROKER ===
# Option 1: GCP Pub/Sub
broker:
  type: gcp-pubsub
  topic: hyperfleet-events
  project_id: my-project-id
  # credentials: Override via BROKER_CREDENTIALS="path/to/credentials.json"
  # project_id: Override via GCP_PROJECT_ID="production-project"

# Option 2: RabbitMQ (alternative configuration)
# broker:
#   type: rabbitmq
#   url: amqp://rabbitmq:5672
#   exchange: hyperfleet
#   # credentials: Override via BROKER_CREDENTIALS="sentinel-user:secret-password"
#   # url: Override via RABBITMQ_URL="amqp://user:pass@prod-rabbitmq:5672"